from io import BytesIO
import PyPDF2
import docx

from summarize_app import config
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain


def read_document(file_content, file_extension):
    """
    Read the content of a document based on its file extension.
    
    Args:
        file_content (bytes): The content of the file.
        file_extension (str): The extension of the file ('pdf' or 'docx').

    Returns:
        str: The extracted text content of the document.
    """
    if file_extension == 'pdf':
        return read_pdf(file_content)
    elif file_extension == 'docx':
        return read_docx(file_content)
    else:
        raise ValueError("Unsupported file extension. Supported extensions are 'pdf' and 'docx'.")


def read_pdf(pdf_content):
    """
    Extract text from a PDF file.
    
    Args:
        pdf_content (bytes): The content of the PDF file.

    Returns:
        str: The extracted text content of the PDF.
    """
    pdf_text = ''
    pdf_reader = PyPDF2.PdfReader(BytesIO(pdf_content))
    for page_num in range(len(pdf_reader.pages)):
        pdf_text += pdf_reader.pages[page_num].extract_text()
    return pdf_text


def read_docx(docx_content):
    """
    Extract text from a DOCX file.
    
    Args:
        docx_content (bytes): The content of the DOCX file.

    Returns:
        str: The extracted text content of the DOCX.
    """
    docx_text = ''
    doc = docx.Document(BytesIO(docx_content))
    for paragraph in doc.paragraphs:
        docx_text += paragraph.text
    return docx_text


def get_llm_response(llm_chain, file_text):
    """
    Get a summary response from the LLM chain.
    
    Args:
        llm_chain (LLMChain): The language model chain to use.
        file_text (str): The text content of the document to summarize.

    Returns:
        str: The summary generated by the language model.
    """
    report_summary = llm_chain.run({
        'uploaded_file': file_text,
    })

    return report_summary


def summarize_report(file_content, file_extension):
    """
    Summarize the content of a document.
    
    Args:
        file_content (bytes): The content of the file.
        file_extension (str): The extension of the file ('pdf' or 'docx').

    Returns:
        str: The summary of the document generated by the language model.
    """
    prompt_template = config.prompt_template
    file_text = read_document(file_content, file_extension)

    prompt = PromptTemplate(
        template=prompt_template,
        input_variables=["uploaded_file"]
    )

    llm = ChatOpenAI(
        model_name=config.openai_llm_name,
        openai_api_key=config.API_KEY,
        temperature=0
    )

    llm_chain = LLMChain(llm=llm, prompt=prompt)

    report_summary = get_llm_response(llm_chain, file_text)

    return report_summary
